function getFonts() {
	return {
		behind_blue_eyes: "Behind Blue Eyes",
		better_land: "Better Land",
		comic_sans_ms: "Comic Sans MS",
		freestyle_script: "Freestyle Script",
		ink_free: "Ink Free",
		lucida_handwriting: "Lucida Handwriting",
		mv_boli: "MV Boli",
		niqueo_bold: "Niqueo Bold",
		polyhedral_lc_bb: "Polyhedral LC BB",
		polyhedral_uc_bb: "Polyhedral UC BB",
		secret_diary: "Secret Diary",
		segoe_print: "Segoe Print",
		segoe_script: "Segoe Script",
		the_girl_next_door: "The Girl Next Door",
		battnise: "Battnise",
		chiller: "Chiller",
		dovahkiin: "Dovahkiin",
		draconic: "Draconic",
		dragonscript: "Dragonscript",
		hpphumblescratch: "HPPHumblescratch",
		inspired: "Inspired",
		kallem: "Kallem",
		kristi: "Kristi",
		pristina: "Pristina",
		quavo: "Quavo",
		salt: "Salt",
		summerfaith: "SummerFaith",
		handayani: "handayani",
	}
}