function getFonts() {
	return {
		adobe_caslon_pro_bold: "Adobe Caslon Pro Bold",
		adobe_caslon_pro: "Adobe Caslon Pro",
		adobe_devanagari: "Adobe Devanagari",
		adobe_garamond_pro_bold: "Adobe Garamond Pro Bold",
		adobe_garamond_pro: "Adobe Garamond Pro",
		agathodaimon: "Agathodaimon",
		agency_fb: "Agency FB",
		algerian: "Algerian",
		amaranth: "Amaranth",
		arial: "Arial",
		arial_black: "Arial Black",
		arial_narrow: "Arial Narrow",
		arial_rounded_mt_bold: "Arial Rounded MT Bold",
		asul: "Asul",
		attika: "Attika",
		attika_black: "Attika Black",
		attika_extra_bold: "Attika Extra Bold",
		attika_medium: "Attika Medium",
		attika_semibold: "Attika SemiBold",
		bahnschrift: "Bahnschrift",
		bahnschrift_condensed: "Bahnschrift Condensed",
		bahnschrift_light_condensed: "Bahnschrift Light Condensed",
		bahnschrift_light_semicondensed: "Bahnschrift Light SemiCondensed",
		bahnschrift_light: "Bahnschrift Light",
		bahnschrift_semibold_condensed: "Bahnschrift SemiBold Condensed",
		bahnschrift_semibold_semiconden: "Bahnschrift SemiBold SemiConden",
		bahnschrift_semibold: "Bahnschrift SemiBold",
		bahnschrift_semicondensed: "Bahnschrift SemiCondensed",
		bahnschrift_semilight_condensed: "Bahnschrift SemiLight Condensed",
		bahnschrift_semilight_semiconde: "Bahnschrift SemiLight SemiConde",
		bahnschrift_semilight: "Bahnschrift SemiLight",
		bailey: "Bailey",
		banthern_personal_use: "Banthern Personal Use",
		basics_serif_free: "Basics Serif Free",
		baskerville_old_face: "Baskerville Old Face",
		battnise: "Battnise",
		bauhaus_93: "Bauhaus 93",
		behind_blue_eyes: "Behind Blue Eyes",
		bell_mt: "Bell MT",
		bente_lite: "Bente Lite",
		berlin_sans_fb_demi: "Berlin Sans FB Demi",
		berlin_sans_fb: "Berlin Sans FB",
		bernard_mt_condensed: "Bernard MT Condensed",
		better_land: "Better Land",
		blackadder_itc: "Blackadder ITC",
		bodoni_mt_black: "Bodoni MT Black",
		bodoni_mt_condensed: "Bodoni MT Condensed",
		bodoni_mt_poster_compressed: "Bodoni MT Poster Compressed",
		bodoni_mt: "Bodoni MT",
		book_antiqua: "Book Antiqua",
		bookinsanity: "Bookinsanity",
		bookman_old_style: "Bookman Old Style",
		bookshelf_symbol_7: "Bookshelf Symbol 7",
		bradley_hand_itc: "Bradley Hand ITC",
		britannic_bold: "Britannic Bold",
		broadway: "Broadway",
		brush_script_mt: "Brush Script MT",
		calibri: "Calibri",
		calibri_light: "Calibri Light",
		californian_fb: "Californian FB",
		calisto_mt: "Calisto MT",
		cambria: "Cambria",
		cambria_math: "Cambria Math",
		candara: "Candara",
		candara_light: "Candara Light",
		cascadia_code_pl: "Cascadia Code PL",
		cascadia_code: "Cascadia Code",
		cascadia_mono_pl: "Cascadia Mono PL",
		cascadia_mono: "Cascadia Mono",
		castellar: "Castellar",
		centaur: "Centaur",
		century: "Century",
		century_gothic: "Century Gothic",
		century_schoolbook: "Century Schoolbook",
		chiller: "Chiller",
		colonna_mt: "Colonna MT",
		comic_sans_ms: "Comic Sans MS",
		consolas: "Consolas",
		constantia: "Constantia",
		cooper_black: "Cooper Black",
		copperplate_gothic_bold: "Copperplate Gothic Bold",
		copperplate_gothic_light: "Copperplate Gothic Light",
		corbel: "Corbel",
		corbel_light: "Corbel Light",
		courier_new: "Courier New",
		courier_prime: "Courier Prime",
		curlz_mt: "Curlz MT",
		depression_mansion: "Depression Mansion",
		dmfontmissing_letters: "Dmfontmissing Letters",
		dnd_infernal: "DnD Infernal",
		dovahkiin: "Dovahkiin",
		draconic: "Draconic",
		dragon_alphabet: "dragon_alphabet",
		dragonic: "Dragonic",
		dragonscript: "Dragonscript",
		dubai: "Dubai",
		dubai_light: "Dubai Light",
		dubai_medium: "Dubai Medium",
		dwarfspirits_bb: "DwarfSpirits BB",
		ebrima: "Ebrima",
		edwardian_script_itc: "Edwardian Script ITC",
		elephant: "Elephant",
		engravers_mt: "Engravers MT",
		eras_bold_itc: "Eras Bold ITC",
		eras_demi_itc: "Eras Demi ITC",
		eras_light_itc: "Eras Light ITC",
		eras_medium_itc: "Eras Medium ITC",
		felix_titling: "Felix Titling",
		font_awesome_5_brands_regular: "Font Awesome 5 Brands Regular",
		font_awesome_5_free_regular: "Font Awesome 5 Free Regular",
		font_awesome_5_free_solid: "Font Awesome 5 Free Solid",
		footlight_mt_light: "Footlight MT Light",
		forte: "Forte",
		franklin_gothic_book: "Franklin Gothic Book",
		franklin_gothic_demi_cond: "Franklin Gothic Demi Cond",
		franklin_gothic_demi: "Franklin Gothic Demi",
		franklin_gothic_heavy: "Franklin Gothic Heavy",
		franklin_gothic_medium_cond: "Franklin Gothic Medium Cond",
		franklin_gothic_medium: "Franklin Gothic Medium",
		freestyle_script: "Freestyle Script",
		french_script_mt: "French Script MT",
		gabriola: "Gabriola",
		gadugi: "Gadugi",
		garamond: "Garamond",
		georgia: "Georgia",
		gigi: "Gigi",
		gill_sans_mt_condensed: "Gill Sans MT Condensed",
		gill_sans_mt_ext_condensed_bold: "Gill Sans MT Ext Condensed Bold",
		gill_sans_mt: "Gill Sans MT",
		gill_sans_ultra_bold_condensed: "Gill Sans Ultra Bold Condensed",
		gill_sans_ultra_bold: "Gill Sans Ultra Bold",
		gliscor_gothic: "Gliscor Gothic",
		gloucester_mt_extra_condensed: "Gloucester MT Extra Condensed",
		goudy_old_style: "Goudy Old Style",
		goudy_stout: "Goudy Stout",
		great_vibes: "Great Vibes",
		haettenschweiler: "Haettenschweiler",
		handayani: "handayani",
		happy_phantom: "Happy Phantom",
		hargael: "Hargael",
		harlow_solid_italic: "Harlow Solid Italic",
		harrington: "Harrington",
		hello_sweety: "Hello Sweety",
		hibrush_demo: "Hibrush_DEMO",
		high_tower_text: "High Tower Text",
		hololens_mdl2_assets: "HoloLens MDL2 Assets",
		homeworld: "Homeworld",
		homeworld_shadow: "Homeworld Shadow",
		hp_simplified_light: "HP Simplified Light",
		hp_simplified: "HP Simplified",
		hpphumblescratch: "HPPHumblescratch",
		impact: "Impact",
		imprint_mt_shadow: "Imprint MT Shadow",
		informal_roman: "Informal Roman",
		ink_free: "Ink Free",
		inspired: "Inspired",
		javanese_text: "Javanese Text",
		jokerman: "Jokerman",
		juice_itc: "Juice ITC",
		kage_freebies_black: "KAGE-Freebies Black",
		kallem: "Kallem",
		knucklehead: "Knucklehead",
		kristen_itc: "Kristen ITC",
		kristi: "Kristi",
		kunstler_script: "Kunstler Script",
		lato: "Lato",
		lato_light: "Lato Light",
		lato_semibold: "Lato Semibold",
		leelawadee: "Leelawadee",
		leelawadee_ui_semilight: "Leelawadee UI Semilight",
		leelawadee_ui: "Leelawadee UI",
		lucida_blackletter: "Lucida Blackletter",
		lucida_bright: "Lucida Bright",
		lucida_calligraphy: "Lucida Calligraphy",
		lucida_console: "Lucida Console",
		lucida_fax: "Lucida Fax",
		lucida_handwriting: "Lucida Handwriting",
		lucida_sans_typewriter: "Lucida Sans Typewriter",
		lucida_sans_unicode: "Lucida Sans Unicode",
		lucida_sans: "Lucida Sans",
		magneto: "Magneto",
		maiandra_gd: "Maiandra GD",
		malgun_gothic_semilight: "Malgun Gothic Semilight",
		malgun_gothic: "Malgun Gothic",
		marlett: "Marlett",
		matura_mt_script_capitals: "Matura MT Script Capitals",
		meillyne: "Meillyne",
		microsoft_himalaya: "Microsoft Himalaya",
		microsoft_jhenghei_light: "Microsoft JhengHei Light",
		microsoft_jhenghei_ui_light: "Microsoft JhengHei UI Light",
		microsoft_jhenghei_ui: "Microsoft JhengHei UI",
		microsoft_jhenghei: "Microsoft JhengHei",
		microsoft_new_tai_lue: "Microsoft New Tai Lue",
		microsoft_phagspa: "Microsoft PhagsPa",
		microsoft_sans_serif: "Microsoft Sans Serif",
		microsoft_tai_le: "Microsoft Tai Le",
		microsoft_uighur: "Microsoft Uighur",
		microsoft_yahei_light: "Microsoft YaHei Light",
		microsoft_yahei_ui_light: "Microsoft YaHei UI Light",
		microsoft_yahei_ui: "Microsoft YaHei UI",
		microsoft_yahei: "Microsoft YaHei",
		microsoft_yi_baiti: "Microsoft Yi Baiti",
		mingliu_extb: "MingLiU-ExtB",
		mingliu_hkscs_extb: "MingLiU_HKSCS-ExtB",
		mistral: "Mistral",
		modern_no_20: "Modern No. 20",
		mondela: "Mondela",
		mongolian_baiti: "Mongolian Baiti",
		monotype_corsiva: "Monotype Corsiva",
		moonshiner_round_oblique: "Moonshiner Round Oblique",
		moonshiner_round: "Moonshiner Round",
		moonshiner_sharp_oblique: "Moonshiner Sharp Oblique",
		moonshiner_sharp: "Moonshiner Sharp",
		ms_gothic: "MS Gothic",
		ms_outlook: "MS Outlook",
		ms_pgothic: "MS PGothic",
		ms_reference_sans_serif: "MS Reference Sans Serif",
		ms_reference_specialty: "MS Reference Specialty",
		ms_ui_gothic: "MS UI Gothic",
		mt_extra: "MT Extra",
		mv_boli: "MV Boli",
		myanmar_text: "Myanmar Text",
		niagara_engraved: "Niagara Engraved",
		niagara_solid: "Niagara Solid",
		niqueo_bold: "Niqueo Bold",
		nirmala_ui_semilight: "Nirmala UI Semilight",
		nirmala_ui: "Nirmala UI",
		nsimsun: "NSimSun",
		ocr_a_extended: "OCR A Extended",
		old_english_text_mt: "Old English Text MT",
		onetwopunch_bb: "OneTwoPunch BB",
		onyx: "Onyx",
		palace_script_mt: "Palace Script MT",
		palatino_linotype: "Palatino Linotype",
		papyrus: "Papyrus",
		parchment: "Parchment",
		perpetua: "Perpetua",
		perpetua_titling_mt: "Perpetua Titling MT",
		playbill: "Playbill",
		pmingliu_extb: "PMingLiU-ExtB",
		polyhedral_lc_bb: "Polyhedral LC BB",
		polyhedral_uc_bb: "Polyhedral UC BB",
		poor_richard: "Poor Richard",
		pristina: "Pristina",
		quavo: "Quavo",
		rage_italic: "Rage Italic",
		rallisha_demo: "Rallisha Demo",
		raventame: "Raventame",
		ravie: "Ravie",
		ringlovely: "Ringlovely",
		roboto: "Roboto",
		roboto_black: "Roboto Black",
		roboto_light: "Roboto Light",
		roboto_medium: "Roboto Medium",
		roboto_thin: "Roboto Thin",
		rockwell: "Rockwell",
		rockwell_condensed: "Rockwell Condensed",
		rockwell_extra_bold: "Rockwell Extra Bold",
		salt: "Salt",
		salted_mocha: "Salted Mocha",
		scaly_sans: "Scaly Sans",
		script_mt_bold: "Script MT Bold",
		secret_diary: "Secret Diary",
		segoe_mdl2_assets: "Segoe MDL2 Assets",
		segoe_print: "Segoe Print",
		segoe_script: "Segoe Script",
		segoe_ui_black: "Segoe UI Black",
		segoe_ui_emoji: "Segoe UI Emoji",
		segoe_ui_historic: "Segoe UI Historic",
		segoe_ui_light: "Segoe UI Light",
		segoe_ui_semibold: "Segoe UI Semibold",
		segoe_ui_semilight: "Segoe UI Semilight",
		segoe_ui_symbol: "Segoe UI Symbol",
		segoe_ui: "Segoe UI",
		senopathi_free_personal_use: "Senopathi Free Personal Use",
		shamery_regular: "Shamery Regular",
		showcard_gothic: "Showcard Gothic",
		showtime: "Showtime",
		signatie: "Signatie",
		simsun: "SimSun",
		simsun_extb: "SimSun-ExtB",
		sitka_banner: "Sitka Banner",
		sitka_display: "Sitka Display",
		sitka_heading: "Sitka Heading",
		sitka_small: "Sitka Small",
		sitka_subheading: "Sitka Subheading",
		sitka_text: "Sitka Text",
		snap_itc: "Snap ITC",
		stencil: "Stencil",
		straightjacket_bb: "StraightJacket BB",
		summerfaith: "SummerFaith",
		sylfaen: "Sylfaen",
		symbol: "Symbol",
		tahoma: "Tahoma",
		teamviewer13: "TeamViewer13",
		teamviewer15: "TeamViewer15",
		tempus_sans_itc: "Tempus Sans ITC",
		the_blacklist: "The Blacklist",
		the_girl_next_door: "The Girl Next Door",
		times_new_roman: "Times New Roman",
		traverse: "TRAVERSE",
		trebuchet_ms: "Trebuchet MS",
		tropikal: "Tropikal",
		tw_cen_mt_condensed_extra_bold: "Tw Cen MT Condensed Extra Bold",
		tw_cen_mt_condensed: "Tw Cen MT Condensed",
		tw_cen_mt: "Tw Cen MT",
		verdana: "Verdana",
		viner_hand_itc: "Viner Hand ITC",
		vivaldi: "Vivaldi",
		vladimir_script: "Vladimir Script",
		we_come_in_peace_bb: "We Come In Peace BB",
		webdings: "Webdings",
		wide_latin: "Wide Latin",
		windlass: "Windlass",
		wingdings: "Wingdings",
		wingdings_2: "Wingdings 2",
		wingdings_3: "Wingdings 3",
		winston_andrews: "Winston Andrews",
		yankee_ghosts_bb: "Yankee Ghosts BB",
		yu_gothic_light: "Yu Gothic Light",
		yu_gothic_medium: "Yu Gothic Medium",
		yu_gothic_ui_light: "Yu Gothic UI Light",
		yu_gothic_ui_semibold: "Yu Gothic UI Semibold",
		yu_gothic_ui_semilight: "Yu Gothic UI Semilight",
		yu_gothic_ui: "Yu Gothic UI",
		yu_gothic: "Yu Gothic",
		zhi_mang_xing: "Zhi Mang Xing",
		zwadobef: "ZWAdobeF",
	}
}